services:
  web:
    build: ./TetrisWeb
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      DB_CONN: "Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
    restart: always

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=ricardoruiz.duckdns.org
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - STAGING=false
    volumes:
      - ./config:/config
    ports:
      - 2000:443
    restart: unless-stopped
    
  db:
    image: postgres
    volumes: 
     #  /var/lib/postgres/data
      - ./schema.sql:/docker-entrypoint-schemadb.d/schema.sql
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=ricardo
      - POSTGRES_DB=ricardodb

  dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
    - 18888:18888

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - /path/to/otel-collector-config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver


volumes:
  PGDATA:
