apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  namespace: ricardo-telem
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'tetrisweb-metrics'
        scrape_interval: 5s
        static_configs:
          - targets: 
            - web:5000