apiVersion: apps/v1
kind: Deployment
metadata:
  name: ricardo-web
  namespace: ricardo-telem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ricardo-web
  template:
    metadata:
      labels:
        app: ricardo-web
    spec:
      containers:
      - name: web
        image: happystar91/running-docker-kubernetes:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_CONN
          value: "host=ricardo-db-svc;password=mypassword;username=ricardo;database=ricardodb"