@TetrisApi_HostAddress = http://localhost:5248

###TEST ENDPOINT FOR CHAT POST not implemented yet
POST {{TetrisApi_HostAddress}}/chat
Content-Type: application/json
{
  "id": 1, 
  "playerid": 1, 
  "message": "Please work or I will desire death",
  "timesent": "12/20/2004",
  player???
}
###TEST ENDPOINT FOR CHAT GET not implemented yet
GET {{TetrisApi_HostAddress}}/chats
###

POST {{TetrisApi_HostAddress}}/api/Player/register
Content-Type: application/json
{
  "Authid": "user123",
  "PlayerQuote": "A super cool quote!",
  "AvatarUrl": "https://example.com/avatar.jpg",
  "ApiKey": "fake-api-key",
  "Isblocked": false
}