@TetrisWeb_HostAddress = http://localhost:5247


POST {{TetrisWeb_HostAddress}}/api/Chat
Content-Type: application/json
{ 
  "Playerid": 1, 
  "Message": "test 1"
  
}
###TEST ENDPOINT FOR CHAT GET not implemented yet
GET {{TetrisWeb_HostAddress}}/api/Chat
###

POST {{TetrisWeb_HostAddress}}/api/Player/register
Content-Type: application/json
{
  "Authid": "testuser3",
  "PlayerQuote": "A super cool quote!",
  "AvatarUrl": "https://example.com/avatar.jpg",
  "ApiKey": "fake-api-key",
  "Isblocked": false
}

###
GET {{TetrisWeb_HostAddress}}/api/boardState

###
POST {{TetrisWeb_HostAddress}}/api/moveLeft/x

###
POST {{TetrisWeb_HostAddress}}/api/moveRight/x

###
POST {{TetrisWeb_HostAddress}}/api/rotate

###
POST {{TetrisWeb_HostAddress}}/api/drop