@TetrisApi_HostAddress = http://localhost:5247

POST {{TetrisApi_HostAddress}}/api/Chat
Content-Type: application/json
{ 
  "Playerid": 1, 
  "Message": "test 1"
  
}
###TEST ENDPOINT FOR CHAT GET not implemented yet
GET {{TetrisApi_HostAddress}}/api/Chat
###

POST {{TetrisApi_HostAddress}}/api/Player/register
Content-Type: application/json
{
  "Authid": "usert",
  "PlayerQuote": "test",
  "AvatarUrl": "https://example.com/avatar.jpg",
  "Isblocked": false
}